import type { PluginListenerHandle } from '@capacitor/core';

import type { IdentityVerificationSheetEventsEnum, IdentityVerificationSheetResultInterface } from './events.enum';
import type { CreateIdentityVerificationSheetOption, InitializeIdentityVerificationSheetOption } from './web';

export * from './events.enum';
export interface StripeIdentityError {
  /**
   * Stripe error code when one is available.
   *
   * @since 5.1.0
   */
  code?: string;
  /**
   * Human-readable error message suitable for logging or display.
   *
   * @since 5.1.0
   */
  message: string;
}

export interface IdentityVerificationResult {
  /**
   * Final state of the presented verification flow.
   *
   * @since 4.2.0
   */
  result: IdentityVerificationSheetResultInterface;
  /**
   * Error details when `result` is `Failed`.
   *
   * @since 4.2.0
   */
  error?: StripeIdentityError;
}

export interface StripeIdentityPlugin {
  /**
   * Initializes Stripe Identity. Call this before `create()` on web.
   *
   * @since 5.4.0
   */
  initialize(options: InitializeIdentityVerificationSheetOption): Promise<void>;
  /**
   * Creates an Identity VerificationSheet from credentials generated by your
   * server. Wait for this Promise or the `Loaded` event before `present()`.
   *
   * @since 5.0.3
   */
  create(options: CreateIdentityVerificationSheetOption): Promise<void>;
  /**
   * Presents the VerificationSheet created by `create()`. Listen for
   * `VerificationResult` to distinguish completed, canceled, and failed flows.
   *
   * @since 5.0.3
   */
  present(): Promise<void>;

  /**
   * Emitted when the VerificationSheet is ready to present.
   *
   * @since 4.2.0
   */
  addListener(
    eventName: IdentityVerificationSheetEventsEnum.Loaded,
    listenerFunc: () => void,
  ): Promise<PluginListenerHandle>;

  /**
   * Emitted when the VerificationSheet could not be created.
   *
   * @since 5.1.0
   */
  addListener(
    eventName: IdentityVerificationSheetEventsEnum.FailedToLoad,
    listenerFunc: (info: StripeIdentityError) => void,
  ): Promise<PluginListenerHandle>;

  /**
   * Emitted when the presented verification flow finishes.
   *
   * @since 4.2.0
   */
  addListener(
    eventName: IdentityVerificationSheetEventsEnum.VerificationResult,
    listenerFunc: (result: IdentityVerificationResult) => void,
  ): Promise<PluginListenerHandle>;
}
