import type { PluginListenerHandle } from '@capacitor/core';

import type { IdentityVerificationSheetEventsEnum, IdentityVerificationSheetResultInterface } from './events.enum';
import type { CreateIdentityVerificationSheetOption, InitializeIdentityVerificationSheetOption } from './web';

export * from './events.enum';
export interface StripeIdentityError {
  /** Stripe error code when one is available. */
  code?: string;
  /** Human-readable error message suitable for logging or display. */
  message: string;
}

export interface IdentityVerificationResult {
  /** Final state of the presented verification flow. */
  result: IdentityVerificationSheetResultInterface;
  /** Error details when `result` is `Failed`. */
  error?: StripeIdentityError;
}

export interface StripeIdentityPlugin {
  /**
   * Initializes Stripe Identity. Call this before `create()` on web.
   */
  initialize(options: InitializeIdentityVerificationSheetOption): Promise<void>;
  /**
   * Creates an Identity VerificationSheet from credentials generated by your
   * server. Wait for this Promise or the `Loaded` event before `present()`.
   */
  create(options: CreateIdentityVerificationSheetOption): Promise<void>;
  /**
   * Presents the VerificationSheet created by `create()`. Listen for
   * `VerificationResult` to distinguish completed, canceled, and failed flows.
   */
  present(): Promise<void>;

  /** Emitted when the VerificationSheet is ready to present. */
  addListener(
    eventName: IdentityVerificationSheetEventsEnum.Loaded,
    listenerFunc: () => void,
  ): Promise<PluginListenerHandle>;

  /** Emitted when the VerificationSheet could not be created. */
  addListener(
    eventName: IdentityVerificationSheetEventsEnum.FailedToLoad,
    listenerFunc: (info: StripeIdentityError) => void,
  ): Promise<PluginListenerHandle>;

  /** Emitted when the presented verification flow finishes. */
  addListener(
    eventName: IdentityVerificationSheetEventsEnum.VerificationResult,
    listenerFunc: (result: IdentityVerificationResult) => void,
  ): Promise<PluginListenerHandle>;
}
