public enum TerminalEvents: String {
    case Loaded = "terminalLoaded"
    case DiscoveringReaders = "terminalDiscoveringReaders"
    case DiscoveredReaders = "terminalDiscoveredReaders"
    case ConnectedReader = "terminalConnectedReader"
    case DisconnectedReader = "terminalDisconnectedReader"
    case ConnectionStatusChange = "terminalConnectionStatusChange"
    case UnexpectedReaderDisconnect = "terminalUnexpectedReaderDisconnect"
    case ConfirmedPaymentIntent = "terminalConfirmedPaymentIntent"
    case CollectedPaymentIntent = "terminalCollectedPaymentIntent"
    case Canceled = "terminalCanceled"
    case Failed = "terminalFailed"
    case RequestedConnectionToken = "terminalRequestedConnectionToken"
    case ReportAvailableUpdate = "terminalReportAvailableUpdate"
    case StartInstallingUpdate = "terminalStartInstallingUpdate"
    case ReaderSoftwareUpdateProgress = "terminalReaderSoftwareUpdateProgress"
    case FinishInstallingUpdate = "terminalFinishInstallingUpdate"
    case BatteryLevel = "terminalBatteryLevel"
    case ReaderEvent = "terminalReaderEvent"
    case RequestDisplayMessage = "terminalRequestDisplayMessage"
    case RequestReaderInput = "terminalRequestReaderInput"
    case PaymentStatusChange = "terminalPaymentStatusChange"
    case ReaderReconnectStarted = "terminalReaderReconnectStarted"
    case ReaderReconnectSucceeded = "terminalReaderReconnectSucceeded"
    case ReaderReconnectFailed = "terminalReaderReconnectFailed"
}
