package com.getcapacitor.community.stripe.terminal;

enum class TerminalEnumEvent(val webEventName: String) {
    Loaded("terminalLoaded"),
    DiscoveringReaders("terminalDiscoveringReaders"),
    DiscoveredReaders("terminalDiscoveredReaders"),
    CancelDiscoveredReaders("terminalCancelDiscoveredReaders"),
    ConnectedReader("terminalConnectedReader"),
    DisconnectedReader("terminalDisconnectedReader"),
    ConnectionStatusChange("terminalConnectionStatusChange"),
    UnexpectedReaderDisconnect("terminalUnexpectedReaderDisconnect"),
    ConfirmedPaymentIntent("terminalConfirmedPaymentIntent"),
    CollectedPaymentIntent("terminalCollectedPaymentIntent"),
    Canceled("terminalCanceled"),
    Failed("terminalFailed"),
    RequestedConnectionToken("terminalRequestedConnectionToken"),
    ReportAvailableUpdate("terminalReportAvailableUpdate"),
    StartInstallingUpdate("terminalStartInstallingUpdate"),
    ReaderSoftwareUpdateProgress("terminalReaderSoftwareUpdateProgress"),
    FinishInstallingUpdate("terminalFinishInstallingUpdate"),
    BatteryLevel("terminalBatteryLevel"),
    ReaderEvent("terminalReaderEvent"),
    RequestDisplayMessage("terminalRequestDisplayMessage"),
    RequestReaderInput("terminalRequestReaderInput"),
    PaymentStatusChange("terminalPaymentStatusChange"),
    ReaderReconnectStarted("terminalReaderReconnectStarted"),
    ReaderReconnectSucceeded("terminalReaderReconnectSucceeded"),
    ReaderReconnectFailed("terminalReaderReconnectFailed"),
}
